common/urls.py
from django.urls import path
from . import views
app_name = 'common'

urlpatterns = [
    path('comadminlogin', views.admin_login, name='admin_login'),
    path('customerlogin', views.customer_login, name='customer_login'),
    path('customersignup', views.customer_signup, name='customer_signup'),
    path('', views.project_home, name='project_home'),
    path('sellerlogin', views.seller_login, name='seller_login'),
    path('sellersignup', views.seller_signup, name='seller_signup'),
    path('mastercommon', views.master_common, name='master_common'),
    path('test', views.test, name='test'),
    path('email_exist', views.email_exist, name='email_exist'),



]

customer/urls.py
from django.urls import path
from . import views
app_name='customer'
urlpatterns=[
    path('customer_home',views.customer_home,name='home'),
    path('ccheckout',views.customer_checkout,name='checkout'),
    path('cmycart',views.customer_mycart,name='mycart'),
    path('cchangepassword',views.customer_changepassword,name='changepassword'),
    path('cproductdetails/<int:p_id>',views.customer_productdetails,name='productdetails'),
    path('cprofile',views.customer_profile,name='customer_profile'),
    path('cmyorders',views.customer_myorders,name='myorders'),
    path('c_logout',views.customer_logout,name='customer_logout'),
    path('master_customer',views.master_customer,name='master_customer'),
    path('change_quantity',views.change_quantity,name ='change_quantity'),
    path('info',views.info,name ='info'),
    path('delete_item/<int:item_id>',views.delete_item, name='delete_item'),
    path('total_price',views.total_price, name='total_price'),


]

ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('customer/', include('customer.urls')),
    path('', include('common.urls')),
    path('ecom_admin/', include('ecom_admin.urls')),
    path('seller/', include('seller.urls')),

]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

customer/models.py
from django.db import models

from common.models import Customer
from seller.models import Product

# Create your models here.

class Cart(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
    
  
    class Meta:
        db_table = 'cart'

class Orders(models.Model):
    cart = models.ForeignKey(Cart,on_delete=models.CASCADE)
    customer = models.ForeignKey(Customer,on_delete=models.CASCADE)
    order_id = models.CharField(max_length = 100)
    ordered_date = models.DateTimeField(auto_now_add=True)
    pincode = models.IntegerField()
    phone = models.BigIntegerField()
    address = models.CharField(max_length = 100)
    place = models.CharField(max_length=50)
    email = models.EmailField()

    class Meta:
        db_table = 'orders'

customer/views.py
from django.http import HttpResponse, JsonResponse
from django.shortcuts import redirect, render
from common.models import Customer
from .models import Cart
from seller.models import Product
from .decorators import auth_customer
import logging

logger = logging.getLogger('django')


@auth_customer
def customer_home(request):
    # customer = Customer.objects.get(id=request.session['customer'])
    products = Product.objects.all()
    return render(request, 'customer/customer_home.html',{'product_data': products})


def customer_checkout(request):
    return render(request, 'customer/checkout.html')


@auth_customer
def customer_mycart(request):
    cart_items = Cart.objects.filter(customer=request.session['customer'])
    return render(request, 'customer/my cart.html', {'cart_items': cart_items})

def customer_myorders(request):
    return render(request, 'customer/my orders.html')


@auth_customer
def customer_productdetails(request, p_id):
    product = Product.objects.get(id=p_id)
    msg = ''
    if request.method == 'POST':
        cart_exist = Cart.objects.filter(
            product=p_id,
            customer=request.session['customer']).exists()

        if not cart_exist:
            cart = Cart(
                customer_id=request.session['customer'], product_id=p_id)
            cart.save()
            return redirect('customer:mycart')
        else:
            msg = 'Item already in cart'
    return render(request, 'customer/product details.html', {'product': product, 'msg': msg})


@auth_customer
def customer_changepassword(request):
    msg = ''
    if request.method == "POST":
        oldpassword = request.POST['old_password']
        newpassword = request.POST['new_password']
        customer = Customer.objects.get(id=request.session['customer'])
        if customer.c_password == oldpassword:
            customer.c_password = newpassword
            customer.save()
            msg = 'Password Updated'
        else:
            msg = 'Passwords does not match'

    return render(request, 'customer/change password.html', {'message': msg})


@auth_customer
def customer_profile(request):
    customer = Customer.objects.get(id=request.session['customer'])
    return render(request, 'customer/customer_profile.html', {'customer_profile': customer})


def master_customer(request):
    customer_name = Customer.objects.get(id=request.session['customer'])
    return render(request, 'customer/master_customer.html',{'customer_nm': customer_name})


def customer_logout(request):
    del request.session['customer']
    request.session.flush()
    return redirect('common:project_home')


def change_quantity(request):
    error_msg = ''
    quantity = int(request.POST['quantity'])
    product_id = int(request.POST['product_id'])
    current_stock = Product.objects.get(id=product_id).p_stock
    if quantity > current_stock:
        error_msg = 'Out of stock'
    else:
        error_msg = 'In stock'
    return JsonResponse({'error_msg': error_msg})

def total_price(request):

    pid = request.POST['pid'] #pid and qty are the key passed from ajax request
    qty = request.POST['qty']
    product = Product.objects.filter(id = pid).values('p_price') # To get the price from the field of the particular product
    total_amount = (int(qty) * product[0]['p_price'] )

    return JsonResponse({'amount': total_amount})

def delete_item(request,item_id):
    item = Cart.objects.get(id=item_id)
    item.delete() 
    return redirect('customer:mycart')


def info(request):
    logger.warning('this is  a warning message')
    a = 10
    b = 0
    try:
        c = a/b
    except Exception as e:
        logger.error('Exception has occured', exc_info=True)
    return HttpResponse('Exception message')

customer/templates/customer/change password.html
{% extends 'customer/master_customer.html' %}
{% load static %}

{% block title %}
<title>Change Password</title>
<link rel="stylesheet" href="{% static 'style/cust_change_pwd.css' %}">
{% endblock %}

{% block content %}
<div class="container">
    <h1>CHANGE PASSWORD </h1><br>
    <p>Enter your details to change your password</p>

    <form method="POST" id="form_id">
        <span>{{message}}</span>
        {% csrf_token %}
        <div class="mb-3">
            <label for="exampleFormControlInput1" class="form-label">Old password</label>
            <input type="password" class="form-control" id="old_password_Field" name="old_password">
        </div>
        <div class="mb-3">
            <label for="exampleFormControlInput1" class="form-label">New password</label>
            <input type="password" class="form-control" id="new_password_Field" name="new_password">
        </div>
        <div class="mb-3">
            <label for="exampleFormControlInput1" class="form-label">Confirm Password</label>
            <input type="password" class="form-control" id="confirm_password_Field" name="confirm_password">
        </div>

        <button type="submit" class="btn btn-success">Change password</button>
    </form>
</div>
{% endblock %}

customer/templates/customer/checkout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    this is the checkout section
</body>
</html>

customer/templates/customer/customer_footer.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="">
    <title>Document</title>
</head>
<body>
    <div class="width">
        
    </div>
</body>
</html>

customer/templates/customer/customer_home.html
{% extends 'customer/master_customer.html' %}
{% load static %}

{% block title %}
<title>Home</title>
<link rel="stylesheet" href="{% static 'style/cust_home_style.css' %}">
{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        {% for prdct in product_data %}
        <div class="col-md-4">
            <div class="card">
                <img src="{{prdct.p_image.url}}" class="card-img-top">
                <div class="popup">
                    <h5 class="card-title"> {{ prdct.p_name | title}} </h5>
                    <p class="card-text">{{ prdct.p_description | title}}</p>
                    <h6 class="card-title">₹{{ prdct.p_price }}</h6>
                    <a href="{% url 'customer:productdetails' prdct.id %}" class="btn btn-warning">View</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

<script>

    const cards = document.querySelectorAll('.card');

    cards.forEach(card => {
        card.addEventListener('mouseenter', showPopup);
        card.addEventListener('mouseleave', hidePopup);
    });

    function showPopup() {
        this.querySelector('.popup').style.opacity = '1';
    }

    function hidePopup() {
        this.querySelector('.popup').style.opacity = '0';
    }


</script>
{% endblock %}

customer/templates/customer/customer_profile.html
{% extends 'customer/master_customer.html' %}
{% load static %}

{% block title %}
<title>Customer Profile</title>
<link rel="stylesheet" href="{% static 'style/cust_profile.css' %}">
{% endblock %}

{% block content %}

<div class="container">
    <h1>CUSTOMER PROFILE</h1>
    <p>Enter your profile details </p>

    <div id="main_div">
        <div>
            <label for="inputEmail4" class="form-label">Name</label>
            <input type="text" class="form-control" id="inputEmail4" name="customer_name"
                value="{{ customer_profile.c_name | title}}" readonly>
        </div>
        <div>
            <label for="inputPassword4" class="form-label">Mobile Number</label>
            <input type="text" class="form-control" id="inputPassword4" name="customer_mobile"
                value="{{ customer_profile.c_mobile }}" readonly>
        </div>
        <div>
            <label for="inputEmail4" class="form-label">Email</label>
            <input type="text" class="form-control" id="inputEmail4" name="customer_phone"
                value="{{ customer_profile.c_email }}" readonly>
        </div><br>
        <a><button class="btn btn-success">Update Profile</button></a>
        <a href="{% url 'customer:changepassword' %}"><button class="btn btn-danger">Change Password</button></a>
    </div>
</div>
{% endblock %}

customer/templates/customer/master_customer.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'style/master_cust_style.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link
        href="https://fonts.googleapis.com/css2?family=Clicker+Script&family=Jost:wght@100;400;500;600&family=Poppins&display=swap"
        rel="stylesheet">
    <script src="https://kit.fontawesome.com/9edefc9b63.js" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"
        integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.min.js"
        integrity="sha384-mQ93GR66B00ZXjt0YO5KlohRA5SY2XofN4zfuZxLkoj1gXtW8ANNCe9d5Y3eG5eD"
        crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.6.4.js"
        integrity="sha256-a9jBBRygX1Bh5lt8GZjXDzyOB+bWve9EiO7tROUtj/E=" crossorigin="anonymous"></script>


    {% block title %}
    <title>Master Customer</title>
    {% endblock %}

</head>

<body>
    <div>
        <div class="first_heading_div">
            <ul class="heading_ul">
                <li data-bs-toggle="dropdown" class="dropdown-toggle">
                    <a href="#"><img src="{% static 'images/united-kingdom.png' %}">ENG</a>
                </li>
                <ul class="dropdown-menu">
                    <li><a class="dropdown-item" href="#"><img src="{% static 'images/germany.png' %}">German</a></li>
                    <li><a class="dropdown-item" href="#"><img src="{% static 'images/france.png' %}">French</a></li>
                </ul>
                <li data-bs-toggle="dropdown" class="dropdown-toggle">
                    <a href="#">
                        <img src="{% static 'images/flag.png' %}">INR</a>
                    </a>
                </li>
                <ul class="dropdown-menu">
                    <li><a class="dropdown-item" href="#"><img src="{% static 'images/united-states.png' %}">USD</a>
                    </li>
                    <li><a class="dropdown-item" href="#"><img
                                src="{% static 'images/united-arab-emirates.png' %}">AED</a></li>
                </ul>
                <li>
                    <a href="#">
                        Track your Orders
                    </a>
                </li>
                <li>
                    <a href="#">
                        My Wishlist
                    </a>
                </li>
                <div class="ul_inside_div">
                    <a href="#"><i class="fa-brands fa-facebook"></i></a>
                    <a href="#"><i class="fa-brands fa-twitter"></i></a>
                    <a href="#"><i class="fa-brands fa-instagram"></i></a>
                    <a href="#"><i class="fa-brands fa-whatsapp"></i></a>
                    <a href="#"><i class="fa-brands fa-linkedin"></i></a>
                </div>

            </ul>

        </div>
    </div>
    <nav class="navbar navbar-expand-lg bg-success">
        <div class="container-fluid">
            <a class="navbar-brand text-light" href="{% url 'customer:home' %}" id="main_heading_a">
                <b>SHOP</b>EHUB</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0 text-light" id="nav_dropdown">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'customer:customer_profile' %}">Men</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'customer:customer_profile' %}">Women</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'customer:myorders' %}">Orders</a>
                    </li>
                </ul>
                <div class="dropdown" id="categories_id">
                    <button class="btn btn-warning dropdown-toggle" type="button" data-bs-toggle="dropdown"
                        aria-expanded="false">
                        Categories
                    </button>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="#">Men</a></li>
                        <li><a class="dropdown-item" href="#">Women</a></li>
                        <li><a class="dropdown-item" href="#">Kids</a></li>
                    </ul>
                </div> &nbsp;&nbsp;
                <form class="d-flex" role="search" id="product_search">
                    <input class="form-control me-2" type="search" placeholder="Search a Product" aria-label="Search">
                    <button class="btn btn-primary" id="search_button" type="submit">Search</button>
                </form>
                <ul class="navbar-nav me-auto mb-2 mb-lg-0 text-light" id="logout_ul">
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                            data-bs-toggle="dropdown" aria-expanded="false">
                            <i class="fa-solid fa-user"></i>
                        </a>
                        <ul class="dropdown-menu">
                            <li ><a class="dropdown-item class_name" href="">Welcome {{ customer_nm.c_name | title }}</a></li>
                            <li>
                                <hr class="dropdown-divider">
                            </li>
                            <li><a class="dropdown-item" href="{% url 'customer:customer_profile' %}">Profile</a></li>
                            <li><a class="dropdown-item" href="{% url 'customer:customer_logout' %}">Logout</a></li>
                        </ul>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="{% url 'customer:mycart' %}"> <i
                                class="fa-solid fa-cart-shopping"></i>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <!-- -------------------------start of second heading------------------------------------ -->

    <div class="main_heading_div">

        <h6>Sale Up To 50% Biggest Discounts. Hurry! Limited Period Registration <a href="{% url 'customer:home' %}"><u>Shop Now</u></a></h6>

    </div>

    <!-- -------------------------end of second heading------------------------------------ -->

    {% block content %}


    {% endblock %}
</body>

</html>

customer/templates/customer/my cart.html
{% extends 'customer/master_customer.html' %}
{% load static %}

{% block title %}
<title>Your Cart</title>
<link rel="stylesheet" href="{% static 'style/cart_style.css' %}">

{% endblock %}

{% block content %}
<div class="cart_heading_div">

    <h2>Cart</h2>
    <p>

        <a href="{% url 'customer:home' %}">Home</a> |
        <a href="#">Cart</a>

    </p>

</div>

<div class="container">
    <div class="table_div">
        <table class="table">
            <thead>
                <th>
                    Product Image
                </th>
                <th>
                    Product Name
                </th>
                <th>
                    Product Category
                </th>
                <th>
                    Product Price
                </th>
                <th>
                    Quantity
                </th>
                <th>
                    Total Price
                </th>
            </thead>
            <!-- {{cart_items}} -->
            {% for item in cart_items %}
            <tr data-item-id="{{ item.product.id }}">
                <td>
                    <img src="{{ item.product.p_image.url }}" width="65px">
                </td>
                <td class="Product_name">
                    {{ item.product.p_name |title}}
                </td>
                <td>
                    {{ item.product.p_category }}
                </td>
                <td>
                    ₹ {{ item.product.p_price }}
                </td>
                <td class="quantity">
                    {% csrf_token %}
                    <input type="number" class="qty-input" min="1" data-item="{{ item.product.id }}"
                        style="width: 50px;"><br>
                    <span id="stock_error"></span>
                    <span id="stock_success"></span>
                </td>
                <td class="total_amount">
                </td>
                <td class="cart_delete">
                    <a href="#" class="delete-link">
                        <p>Delete</p>
                    </a>
                </td>
            </tr>
            {% endfor %}
        </table>
    </div>

    <div class="amount_div">

        <table class="amount_table">
            <tr>
                <td>Grandtotal</td>
                <td class="grand_total">
                </td>
            </tr>
        </table>
        <div>
            <button class="btn btn-success">Place Order</button>
        </div>




    </div>
</div>

<script>

    $(document).ready(function () {
        $.ajaxSetup({
            headers: {
                "X-CSRFToken": $('[name=csrfmiddlewaretoken]').val()
            }
        })

        $('.qty-input').change(function () {

            $.ajax({

                type: 'POST',
                url: "{% url 'customer:change_quantity' %}",
                data: {
                    'product_id': $(this).attr('data-item'),
                    'quantity': $(this).val()
                },


                success: function (response) {
                    let error = response.error_msg
                    if (error == "In stock") {
                        $('#stock_error').html(error)
                        $('#stock_error').css('color', 'green')

                    } else {
                        $('#stock_error').html(error)
                        $('#stock_error').css('color', 'red')
                    }
                    $('#stock_error').html(error)


                }
            })
        })
        displayTotalAmount()
        $.ajaxSetup({
            headers: {
                "X-CSRFToken": '{{ csrf_token }}'
            }
        })

        $('.quantity input').on('change', function () {
            let qty = $(this).val()
            let pid = $(this).attr('data-item')

            $.ajax({
                url: "{% url 'customer:total_price' %}",
                method: 'POST',
                data: {
                    'pid': pid,
                    'qty': qty
                },
                success: function (response) {
                    $(this).closest('tr').find('.total_amount').html('₹' + response.amount);
                    displayTotalAmount()
                }.bind(this)
            });
        });
    })

    function displayTotalAmount() {
        let amount_cells = document.getElementsByClassName('total_amount');
        let total = 0;

        for (let i = 0; i < amount_cells.length; i++) {
            let amount = parseFloat(amount_cells[i].textContent.replace('₹', '')); // Remove the ₹ symbol
            total += amount;
        }

        $('.grand_total').html('₹' + total);
    }


    // $.ajaxSetup({
    //     headers: {
    //         "X-CSRFToken": '{{ csrf_token }}'
    //     }
    // })

    // $('.delete-link').on('click', function () {


    // })

</script>
{% endblock %}

customer/templates/customer/my orders.html
{% extends 'customer/master_customer.html' %}
{% load static %}

{% block title %}
<title>My Orders</title>
<link rel="stylesheet" href="{% static 'style/cust_orders_style.css' %}">
{% endblock %}

{% block content %}
<div class="container main_div">
    <div class="orders_heading_div">
        <p class="order_heading"><b>Order Placed on : </b>July 16,2023</p>
        <p class="order_heading"><b>Grand Total : </b>₹5999/-</p>
        <p class="order_heading"><b>Order ID : </b>SEH12304082023</p>

    </div>
    <hr>
    <div class="row main_row">
        <div class="col-lg-2">
            <img src="{% static 'images/blue_shirt.jpg' %}" alt="" width="80px">
        </div>
        <div class="col-lg-3 ptags_div">
            <p>Mens Tshirts</p> <br>
            <p>Quantity 5</p> <br>
            <p>₹2978/-</p>
        </div>
    </div>
    <hr>
    <div class="row main_row">
        <div class="col-lg-2">
            <img src="{% static 'images/blue_shirt.jpg' %}" alt="" width="80px">
        </div>
        <div class="col-lg-3 ptags_div">
            <p>Mens Tshirts</p> <br>
            <p>Quantity 5</p> <br>
            <p>₹2978/-</p>
        </div>
    </div>
</div>

{% endblock %}

customer/templates/customer/product details.html
{% extends 'customer/master_customer.html' %}
{% load static %}

{% block title %}
<title>Your Cart</title>
<link rel="stylesheet" href="{% static 'style/product_details_style.css' %}">

{% endblock %}

{% block content %}

<div class="card">
    <form method="POST">
        {% csrf_token %}
        <div class="row g-0 main_div">
            <div class="col-lg-6 image_div">
                <img src="{{ product.p_image.url }}" class="img-fluid rounded-start" alt="..." width="280px">
            </div>
            <div class="col-lg-6">
                <div class="card-body">
                    <span>{{ msg }}</span>
                    <h5 class="card-title">{{ product.p_name }}</h5>
                    <p class="card-text">{{ product.p_description }}</p>
                    <h4>MRP ₹{{product.p_price}} &nbsp; <h4> <strike>₹1200</strike> (25% OFF)</h4>
                    </h4>
                    <p id="tax_p">Inclusive of all Taxes</p>
                    <button id="cart_button" type="submit" class="btn btn-danger"><i
                            class="fa-sharp fa-solid fa-bag-shopping" style="color: #ffffff;"></i>Cart</button>
                    <button class="btn btn-outline-success" type="button"><i class="fa-regular fa-heart"></i>Wishlist</button>
                </div>
            </div>
        </div>

    </form>
</div>

{% endblock %}