common/urls.py
from django.urls import path
from . import views
app_name = 'common'

urlpatterns = [
    path('comadminlogin', views.admin_login, name='admin_login'),
    path('customerlogin', views.customer_login, name='customer_login'),
    path('customersignup', views.customer_signup, name='customer_signup'),
    path('', views.project_home, name='project_home'),
    path('sellerlogin', views.seller_login, name='seller_login'),
    path('sellersignup', views.seller_signup, name='seller_signup'),
    path('mastercommon', views.master_common, name='master_common'),
    path('test', views.test, name='test'),
    path('email_exist', views.email_exist, name='email_exist'),



]

ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('customer/', include('customer.urls')),
    path('', include('common.urls')),
    path('ecom_admin/', include('ecom_admin.urls')),
    path('seller/', include('seller.urls')),

]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

seller/urls.py
from django.urls import path
from . import views
app_name='seller'


urlpatterns=[
    path('addproduct',views.add_product,name='add_product'),
    path('changepassword',views.change_password,name='changepassword'),
    path('sellerhome',views.seller_home,name='seller_home'),
    path('productcatalogue',views.product_catalogue),
    path('sellerprofile',views.seller_profile,name='seller_profile'),
    path('updatestock',views.update_stock,name='update_stock'),
    path('vieworders',views.view_orders),
    path('master_seller',views.master_seller,name='master_seller'),
    path('view_product',views.view_product,name='view_product'),
    path('s_logout',views.seller_logout,name='seller_logout'),
    path('stock_update',views.stock_update,name='stock_update'),



]

seller/models.py
from django.db import models
from common.models import Seller

# Create your models here.


class Product(models.Model):
    seller = models.ForeignKey(Seller, on_delete=models.CASCADE)
    p_name = models.CharField(max_length=50)
    p_description = models.CharField(max_length=50)
    p_number = models.BigIntegerField()
    p_stock = models.BigIntegerField()
    p_price = models.BigIntegerField()
    p_category = models.CharField(max_length=50)
    p_image = models.ImageField(upload_to='product/')

    class Meta:
        db_table = 'product'

seller/views.py
from django.shortcuts import redirect, render
from common.models import Seller
from seller.decorators import auth_seller
from seller.models import Product
from django.http import JsonResponse


# @auth_seller
def add_product(request):
    msg = ''
    if request.method == 'POST':
        pname = request.POST['p_name']
        pdescription = request.POST['p_description']
        pcategory = request.POST['p_category']
        pnumber = request.POST['p_number']
        pstock = request.POST['p_current_stock']
        pprice = request.POST['p_price']
        pimage = request.FILES['p_image']
        new_product = Product(
            p_name=pname,
            p_description=pdescription,
            p_category=pcategory,
            p_number=pnumber,
            p_stock=pstock,
            p_price=pprice,
            p_image=pimage,
            seller_id=request.session['seller']
        )

        new_product.save()
        msg = 'Product added successfully'

    return render(request, 'seller/add product.html', {'success_message': msg})


# @auth_seller
def change_password(request):
    msg = ''
    if request.method == 'POST':
        oldpassword = request.POST['old_password']
        newpassword = request.POST['new_password']
        seller = Seller.objects.get(id=request.session['seller'])
        if seller.s_password == oldpassword:
            seller.s_password = newpassword
            seller.save()
            msg = 'password updated'
        else:
            msg = 'password does not match'
    return render(request, 'seller/change password.html', {'password_message': msg})


# @auth_seller
def seller_home(request):
    seller_data = Seller.objects.get(id=request.session['seller'])
    return render(request, 'seller/seller home.html', {'seller_data': seller_data})


def product_catalogue(request):
    return render(request, 'seller/product catalogue.html')


# @auth_seller
def seller_profile(request):
    seller = Seller.objects.get(id=request.session['seller'])
    return render(request, 'seller/seller profile.html', {'seller_profile_data': seller})

# @auth_seller
def update_stock(request):
    products = Product.objects.filter(
        seller=request.session['seller']).values('id', 'p_name')
    if request.method == 'POST':
        prodnum = request.POST['p_number']
        new_stock = request.POST['new_stock']
        product1 = Product.objects.get(id=prodnum)
        product1.p_stock += int(new_stock)
        product1.save() 

    return render(request, 'seller/update stock.html', {'products': products})

# @auth_seller
def view_product(request):
    sellerid = request.session['seller']
    product = Product.objects.filter(seller_id=sellerid)
    return render(request, 'seller/view_product.html', {'product_message': product})

# @auth_seller
def view_orders(request):
    return render(request, 'seller/view orders.html')

# @auth_seller
def master_seller(request):
    return render(request, 'seller/master_seller.html')

def seller_logout(request):
    del request.session['seller']
    request.session.flush()
    return redirect('common:project_home')

def stock_update(request):
    product_id = request.POST['product_id']
    product = Product.objects.filter(id=product_id).values('p_stock')
    current_stock = product[0]['p_stock']
    return JsonResponse({'stock': current_stock})

seller/templates/seller/add product.html
{% extends 'seller/master_seller.html' %}
{% load static %}

{% block title %}
<title>Add Product</title>
<link rel="stylesheet" href="{% static 'style/add_product_style.css' %}">
{% endblock %}

{% block content %}
<h1>ADD PRODUCT</h1><br>
<div class="container">
    <form method="POST" enctype="multipart/form-data" id="form_id">
        {% csrf_token %}
        {{success_message}}
        <div class="mb-3">
            <label for="exampleFormControlInput1" class="form-label">Product Name</label>
            <input type="text" class="form-control" id="nameField" name="p_name">
        </div>
        <div class="mb-3">
            <label for="exampleFormControlTextarea1" class="form-label">Product Description</label>
            <textarea class="form-control" id="descriptionField" rows="1" name="p_description"></textarea>
        </div>
        <div class="mb-3">
            <label for="exampleFormControlInput1" class="form-label">Product Category</label>
            <input type="text" class="form-control" id="categoryField" name="p_category">
        </div>
        <div class="mb-3">
            <label for="exampleFormControlInput1" class="form-label">Product Number</label>
            <input type="text" class="form-control" id="numberField" name="p_number">
        </div>
        <div class="mb-3">
            <label for="exampleFormControlInput1" class="form-label">Current Stock</label>
            <input type="text" class="form-control" id="stockField" name="p_current_stock">
        </div>
        <div class="mb-3">
            <label for="exampleFormControlInput1" class="form-label">Price</label>
            <input type="text" class="form-control" id="priceField" name="p_price">
        </div>
        <label for="exampleFormControlInput1" class="form-label">Product Image</label>
        <div class="input-group mb-3">
            <input type="FILE" class="form-control" id="inputGroupFile02" name="p_image">
            <label class="input-group-text" for="inputGroupFile02">Upload</label>
        </div>
        <button type="submit" class="btn btn-success">Submit Product</button>
    </form>
</div>
<br>
{% endblock %}

seller/templates/seller/change password.html
{% extends 'seller/master_seller.html' %}
{% load static %}

{% block title %}
<title>Change Password</title>
<link rel="stylesheet" href="{% static 'style/seller_change_pwd.css' %}">
{% endblock %}

{% block content %}
<h1>CHANGE PASSWORD</h1><br>
<div class="container">
    <form method="POST" id="form_id">
        {% csrf_token %}
        {{password_message}}
        <div class="mb-3">
            <label for="exampleFormControlInput1" class="form-label">old password</label>
            <input type="password" class="form-control" name="old_password">
        </div>
        <div class="mb-3">
            <label for="exampleFormControlInput1" class="form-label">new password</label>
            <input type="password" class="form-control" name="new_password">
        </div>
        <div class="mb-3">
            <label for="exampleFormControlInput1" class="form-label">confirm Password</label>
            <input type="password" class="form-control" name="confirm_password">
        </div>

        <button type="submit" class="btn btn-success">Change password</button>
        {{ error }} {{ success }}
    </form>
</div>
{% endblock %}

seller/templates/seller/master_seller.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'style/master_seller_style.css' %}">
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"
        integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.min.js"
        integrity="sha384-mQ93GR66B00ZXjt0YO5KlohRA5SY2XofN4zfuZxLkoj1gXtW8ANNCe9d5Y3eG5eD"
        crossorigin="anonymous"></script>
    <script src=" https://code.jquery.com/jquery-3.6.4.js"
        integrity="sha256-a9jBBRygX1Bh5lt8GZjXDzyOB+bWve9EiO7tROUtj/E=" crossorigin="anonymous">
        </script>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link
        href="https://fonts.googleapis.com/css2?family=Clicker+Script&family=Jost:wght@100;400;500;600&family=Poppins&display=swap"
        rel="stylesheet">
    <script src="https://kit.fontawesome.com/9edefc9b63.js" crossorigin="anonymous"></script>
    {% block title %}
    <title>Master seller</title>
    {% endblock %}
</head>

<body>
    <div>
        <!-- -------------------------start of first heading------------------------------------ -->
        <div class="first_heading_div">
            <ul class="heading_ul">
                <li>
                    <a href="#">About</a>
                </li>
                <li>
                    <a href="#">
                        Privacy
                    </a>
                </li>
                <li>
                    <a href="#">
                        FAQ
                    </a>
                </li>
                <li>
                    <a href="#">
                        Careers
                    </a>
                </li>
                <li>
                    <a href="#">
                        Track your Order
                    </a>
                </li>
                <li>
                    <a href="#">
                        My Wishlist
                    </a>
                </li>
                <div class="ul_inside_div">
                    <a href="#"><i class="fa-brands fa-facebook"></i></a>
                    <a href="#"><i class="fa-brands fa-twitter"></i></a>
                    <a href="#"><i class="fa-brands fa-instagram"></i></a>
                    <a href="#"><i class="fa-brands fa-whatsapp"></i></a>
                    <a href="#"><i class="fa-brands fa-linkedin"></i></a>
                </div>

            </ul>

        </div>
        <!-- -------------------------end of first heading------------------------------------ -->

        <nav class="navbar navbar-expand-lg bg-success">
            <div class="container-fluid">
                <a class="navbar-brand text-light" href="#"><b>SHOP</b>EHUB</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0 text-light">
                        <li class="nav-item">
                            <a class="nav-link" aria-current="page" href="{% url 'seller:seller_home' %}">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'seller:add_product' %}">Add Product</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'seller:update_stock' %}">Update
                                Stock</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'seller:seller_profile' %}">Profile</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'seller:view_product' %}">View Products</a>
                        </li>
                    </ul>

                    <ul class="navbar-nav me-auto mb-2 mb-lg-0 text-light" style="padding-left: 40px;">
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'seller:changepassword' %}">Change
                                Password</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'seller:seller_logout' %}">Logout</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>

         <!-- -------------------------start of second heading------------------------------------ -->

         <div class="main_heading_div">

            <h6>Sale Up To 50% Biggest Discounts. Hurry! Limited Period Registration  <u><a href="#">Shop Now</a></u>

            </h6>

        </div>
        <!-- -------------------------end of second heading------------------------------------ -->
        {% block content %}

        {% endblock %}
    </div>
</body>

</html>

seller/templates/seller/product catalogue.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
</body>
</html>

seller/templates/seller/seller home.html
{% extends 'seller/master_seller.html' %}
{% load static %}

{% block title %}
<title>Seller Home</title>
{% endblock %}

{% block content %}
<h6>Welcome to ShopEhuB, {{ seller_data.s_name | title }} </h6>
<div class="maindiv">
    <div class="image_div">
        <!-- <img src="{% static 'images/standing_man.png' %}" height="500px" width="400px" alt="" class="imagediv2"> -->
    </div>
    <div class="sale_main_heading" style="margin-top: 140px;">
        <div class="sale_heading">
            <h6><i>New Year's Sale</i></h6>
        </div>
        <div class="yahyasample">
            <h1>Men's Clothing</h1>
        </div>
        <h4>UP TO 50% OFF</h4>
        <button class="btn btn-warning" type="submit"> <b>Shop Now !!</b></button>
    </div>
</div>
{% endblock %}

seller/templates/seller/seller profile.html
{% extends 'seller/master_seller.html' %}
{% load static %}

{% block title %}
<title>Seller Profile</title>
<link rel="stylesheet" href="{% static 'style/seller_profile.css' %}">
{% endblock %}

{% block content %}
<div class="container">
    <h1>SELLER PROFILE</h1><br>
    <p>Enter your profile details </p>

    <div>
        <img src="{{ seller_profile_data.s_image.url }}" alt="" width="100px">

    </div><br>
    <div>
        <label for="inputEmail4" class="form-label">Name</label>
        <input type="text" class="form-control" id="inputEmail4" placeholder="Enter your Name"
            value="{{ seller_profile_data.s_name | title}}" readonly>
    </div><br>
    <div>
        <label for="inputPassword4" class="form-label">Email Address</label>&nbsp;&nbsp;&nbsp;&nbsp;
        <input type="email" class="form-control" id="inputPassword4" placeholder="Enter your Email"
            value="{{ seller_profile_data.s_email }}" readonly>
    </div><br>
    <div>
        <label for="inputEmail4" class="form-label">Phone Number</label>&nbsp;&nbsp;&nbsp;
        <input type="text" class="form-control" id="inputEmail4" placeholder="Enter your Phone Number"
            value="{{ seller_profile_data.s_mobile }}" readonly>
    </div>
</div>
{% endblock %}

seller/templates/seller/update stock.html
{% extends 'seller/master_seller.html' %}
{% load static %}

{% block title %}
<title>Update Stock</title>
<link rel="stylesheet" href="{% static 'style/update_stock_style.css' %}">

{% endblock %}

{% block content %}
<h1>UPDATE STOCK</h1><br>
<div class="container">
    <form method="POST" id="form_id">
        {% csrf_token %}
        <div class="mb-3">
            <label for="exampleFormControlTextarea1" class="form-label">Product No</label>
            <select name="p_number" id="product" class="form-control" data-bs-toggle="dropdown" aria-expanded="false">
                {% for product in products %}
                <option value="{{product.id}}">{{ product.p_name | title }}</option>
                {% endfor %}
            </select>
        </div>
        <div class="mb-3">
            <label for="exampleFormControlInput1" class="form-label">Current Stock</label>
            <input type="text" class="form-control" id="stock_field" name="p_category">
        </div>
        <div class="mb-3">
            <label for="exampleFormControlInput1" class="form-label">New Stock</label>
            <input type="number" class="form-control" id="categoryField" name="new_stock" min="1">
        </div>
        <button type="submit" class="btn btn-success">Update</button>
    </form>
</div>
<script>
    $(document).ready(function () {
        $.ajaxSetup({
            headers: {
                "X-CSRFToken": $('[name=csrfmiddlewaretoken]').val()
            }
        })

        $('#product').change(function () {

            $.ajax({

                type: 'POST',
                url: "{% url 'seller:stock_update' %}",
                data: {
                    'product_id': $(this).val()
                },


                success: function (response) {

                    let res = response.stock
                    $('#stock_field').val(res)
                }
            })
        })
    })

</script>
{% endblock %}

seller/templates/seller/view_product.html
{% extends 'seller/master_seller.html' %}
{% load static %}

{% block title %}
<title>View Product</title>
<style>
    .card:hover {
        transform: scale(1.0);
        box-shadow: 0 10px 20px rgba(0, 0, 0, .12), 0 4px 8px rgba(0, 0, 0, .06);
    }
</style>

{% endblock %}

{% block content %}
<br><br>
<div class="container">

    <div class="row">
        {% for prdct in product_message %}
        <div class="col-md-4">
            <div class="card" style="width: 18rem;margin: 1%; ">
                <img src="{{prdct.p_image.url}}" class="card-img-top" alt="..." height="200px">
                <div class="card-body">
                    <h5 class="card-title"> {{prdct.p_name}} </h5>
                    <p class="card-text"> {{prdct.p_description}} </p>
                    <h6 class="card-title">₹{{prdct.p_price}}</h6>
                    <a href="#" class="btn btn-primary">Go somewhere</a>
                </div>

            </div>

        </div>
        {% endfor %}

    </div>


</div>

{% endblock %}