common/urls.py
from django.urls import path
from . import views
app_name = 'common'

urlpatterns = [
    path('comadminlogin', views.admin_login, name='admin_login'),
    path('customerlogin', views.customer_login, name='customer_login'),
    path('customersignup', views.customer_signup, name='customer_signup'),
    path('', views.project_home, name='project_home'),
    path('sellerlogin', views.seller_login, name='seller_login'),
    path('sellersignup', views.seller_signup, name='seller_signup'),
    path('mastercommon', views.master_common, name='master_common'),
    path('test', views.test, name='test'),
    path('email_exist', views.email_exist, name='email_exist'),



]

ecom_admin/urls.py
from django.urls import path
from .import views
app_name='ecom_admin'


urlpatterns = [
    path('approve sellers',views.approve_sellers,name='approve sellers'),
    path('ecom_home',views.ecom_home,name='ecom_home'),
    path('view customers',views.view_customers,name='view customers'),
    path('view sellers',views.view_sellers,name='view sellers'),
    path('view orders',views.view_orders,name='view orders'),
    path('recent updates',views.recent_updates,name='recent updates'),
    path('view products',views.view_products,name='view products'),
    path('remove customer',views.remove_customer,name='remove customer'),
    path('remove seller',views.remove_seller,name='remove seller'),
    path('remove product',views.remove_product,name='remove product'),
    path('admin_master',views.admin_master,name='admin_master'),
    path('admin_login',views.admin_login,name='admin_login'),


    

]

ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('customer/', include('customer.urls')),
    path('', include('common.urls')),
    path('ecom_admin/', include('ecom_admin.urls')),
    path('seller/', include('seller.urls')),

]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecom_admin/models.py
from django.db import models

# Create your models here.

# class Users(models.Model):
#     name = models.CharField(max_length=20)
#     email = models.CharField(max_length=40)
#     password = models.CharField(max_length=25)
#     age = models.IntegerField()
#     phone_number = models.BigIntegerField()
#     dob = models.DateField()
#     gender = models.CharField(max_length=10)
#     address = models.TextField()



 

ecom_admin/views.py
from django.shortcuts import render

from common.models import Customer, Seller
from seller.models import Product


def approve_sellers(request):
    return render(request, 'ecom_admin/approve sellers.html')

def admin_login(request):
    return render(request, 'ecom_admin/admin_login.html')


def ecom_home(request):
    customer_count = Customer.objects.count()
    seller_count = Seller.objects.count()
    product_count = Product.objects.count()
    return render(request, 'ecom_admin/home.html', {'c_count': customer_count,'s_count': seller_count,'p_count':product_count})


def view_customers(request):
    customers = Customer.objects.all()
    return render(request, 'ecom_admin/view customers.html',{'customers':customers})


def view_sellers(request):
    sellers = Seller.objects.all()
    return render(request, 'ecom_admin/view sellers.html',{'sellers':sellers})


def view_orders(request):
    return render(request, 'ecom_admin/view orders.html')


def recent_updates(request):
    return render(request, 'ecom_admin/recent updates.html')


def view_products(request):
    return render(request, 'ecom_admin/view products.html')


def remove_customer(request):
    return render(request, 'ecom_admin/remove customer.html')


def remove_seller(request):
    return render(request, 'ecom_admin/remove seller.html')


def remove_product(request):
    return render(request, 'ecom_admin/remove product.html')


def admin_master(request):
    return render(request, 'ecom_admin/admin_master.html')

ecom_admin/templates/ecom_admin/admin_master.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block title %}
    <title>SHOP E HUB</title>
    {% endblock %}

    <!-- BootstrapCss v5.3.0 -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <link rel="stylesheet" href="/static/style/admin_master_style.css">
    <link
        href="https://fonts.googleapis.com/css2?family=Clicker+Script&family=Jost:wght@100;400;500;600&family=Poppins&display=swap"
        rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.min.js"
        integrity="sha384-mQ93GR66B00ZXjt0YO5KlohRA5SY2XofN4zfuZxLkoj1gXtW8ANNCe9d5Y3eG5eD"
        crossorigin="anonymous"></script>
    {% comment %}
    <link rel="stylesheet" href="/static/style/admin_master_style.css">
    <link
        href="https://fonts.googleapis.com/css2?family=Clicker+Script&family=Jost:wght@100;400;500;600&family=Poppins&display=swap"
        rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.min.js"
        integrity="sha384-mQ93GR66B00ZXjt0YO5KlohRA5SY2XofN4zfuZxLkoj1gXtW8ANNCe9d5Y3eG5eD"
        crossorigin="anonymous"></script>
    {% endcomment %}

    {% block style %}

    {% endblock %}
    <style>
        #category-hover {
            display: none;
        }

        #category-hover:hover {
            display: block;
        }

        #item-0 {

            background-color: #7B9579;
            grid-row-start: 1;
            grid-column-start: 1;

            grid-row-end: 3;
            grid-column-end: 3;

        }
    </style>
</head>

<body>
    <section>
        <nav class="navbar navbar-expand-lg navbar-light bg-white pt-3 pb-3">
            <div class="container">
                <a class="navbar-brand" href="{% url 'ecom_admin:ecom_home' %}"><img src="" alt=""><b>SHOP</b>EHUB</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">

                    <ul class="navbar-nav me-auto mx-auto mb-2 mb-lg-0">

                    </ul>

                    <form class="d-flex">
                        <ul class="navbar-nav me-2 mb-2 mb-lg-0">
                            <li class="nav-item">
                                <a class="nav-link active" href="{% url 'admin:login' %}"><svg
                                        xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor"
                                        class="bi bi-box-arrow-left" viewBox="0 0 16 16">
                                        <path fill-rule="evenodd"
                                            d="M6 12.5a.5.5 0 0 0 .5.5h8a.5.5 0 0 0 .5-.5v-9a.5.5 0 0 0-.5-.5h-8a.5.5 0 0 0-.5.5v2a.5.5 0 0 1-1 0v-2A1.5 1.5 0 0 1 6.5 2h8A1.5 1.5 0 0 1 16 3.5v9a1.5 1.5 0 0 1-1.5 1.5h-8A1.5 1.5 0 0 1 5 12.5v-2a.5.5 0 0 1 1 0v2z" />
                                        <path fill-rule="evenodd"
                                            d="M.146 8.354a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L1.707 7.5H10.5a.5.5 0 0 1 0 1H1.707l2.147 2.146a.5.5 0 0 1-.708.708l-3-3z" />
                                    </svg></a>
                            </li>
                        </ul>
                    </form>
                </div>
            </div>
        </nav>
    </section>

    <section>
        <nav class="navbar navbar-expand-lg navbar-light bg-success pt-1 pb-1">
            <div class="container">
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mx-auto mb-2 mb-lg-0">

                        <div class="category-emt me-2">
                            <li class="nav-item me-5">
                                <a class="nav-link active text-light" aria-current="page"
                                    href="{% url 'ecom_admin:ecom_home' %}">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                                        class="bi bi-graph-up-arrow" viewBox="0 0 16 16">
                                        <path fill-rule="evenodd"
                                            d="M0 0h1v15h15v1H0V0Zm10 3.5a.5.5 0 0 1 .5-.5h4a.5.5 0 0 1 .5.5v4a.5.5 0 0 1-1 0V4.9l-3.613 4.417a.5.5 0 0 1-.74.037L7.06 6.767l-3.656 5.027a.5.5 0 0 1-.808-.588l4-5.5a.5.5 0 0 1 .758-.06l2.609 2.61L13.445 4H10.5a.5.5 0 0 1-.5-.5Z" />
                                    </svg>
                                    Dashboard <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16"
                                        fill="currentColor" class="bi bi-caret-down-fill" viewBox="0 0 16 16">
                                        <path
                                            d="M7.247 11.14 2.451 5.658C1.885 5.013 2.345 4 3.204 4h9.592a1 1 0 0 1 .753 1.659l-4.796 5.48a1 1 0 0 1-1.506 0z" />
                                    </svg>
                                </a>
                            </li>
                        </div>

                        <div class="category-emt me-2">
                            <li class="nav-item me-5">
                                <a class="nav-link active text-light" aria-current="page"
                                    href="{% url 'ecom_admin:view customers' %}">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                                        class="bi bi-collection" viewBox="0 0 16 16">
                                        <path
                                            d="M2.5 3.5a.5.5 0 0 1 0-1h11a.5.5 0 0 1 0 1h-11zm2-2a.5.5 0 0 1 0-1h7a.5.5 0 0 1 0 1h-7zM0 13a1.5 1.5 0 0 0 1.5 1.5h13A1.5 1.5 0 0 0 16 13V6a1.5 1.5 0 0 0-1.5-1.5h-13A1.5 1.5 0 0 0 0 6v7zm1.5.5A.5.5 0 0 1 1 13V6a.5.5 0 0 1 .5-.5h13a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-.5.5h-13z" />
                                    </svg>
                                    Customers <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16"
                                        fill="currentColor" class="bi bi-caret-down-fill" viewBox="0 0 16 16">
                                        <path
                                            d="M7.247 11.14 2.451 5.658C1.885 5.013 2.345 4 3.204 4h9.592a1 1 0 0 1 .753 1.659l-4.796 5.48a1 1 0 0 1-1.506 0z" />
                                    </svg>
                                </a>
                            </li>
                        </div>

                        <div class="category-emt me-2">
                            <li class="nav-item me-5">
                                <a class="nav-link active text-light" aria-current="page"
                                    href="{% url 'ecom_admin:view sellers' %}">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                                        class="bi bi-bag" viewBox="0 0 16 16">
                                        <path
                                            d="M8 1a2.5 2.5 0 0 1 2.5 2.5V4h-5v-.5A2.5 2.5 0 0 1 8 1zm3.5 3v-.5a3.5 3.5 0 1 0-7 0V4H1v10a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2V4h-3.5zM2 5h12v9a1 1 0 0 1-1 1H3a1 1 0 0 1-1-1V5z" />
                                    </svg>
                                    Sellers <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16"
                                        fill="currentColor" class="bi bi-caret-down-fill" viewBox="0 0 16 16">
                                        <path
                                            d="M7.247 11.14 2.451 5.658C1.885 5.013 2.345 4 3.204 4h9.592a1 1 0 0 1 .753 1.659l-4.796 5.48a1 1 0 0 1-1.506 0z" />
                                    </svg></a>
                            </li>
                        </div>

                        <div class="category-emt me-2">
                            <li class="nav-item me-5">
                                <a class="nav-link active text-light" aria-current="page"
                                    href="{% url 'ecom_admin:ecom_home' %}">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                                        class="bi bi-boxes" viewBox="0 0 16 16">
                                        <path
                                            d="M7.752.066a.5.5 0 0 1 .496 0l3.75 2.143a.5.5 0 0 1 .252.434v3.995l3.498 2A.5.5 0 0 1 16 9.07v4.286a.5.5 0 0 1-.252.434l-3.75 2.143a.5.5 0 0 1-.496 0l-3.502-2-3.502 2.001a.5.5 0 0 1-.496 0l-3.75-2.143A.5.5 0 0 1 0 13.357V9.071a.5.5 0 0 1 .252-.434L3.75 6.638V2.643a.5.5 0 0 1 .252-.434L7.752.066ZM4.25 7.504 1.508 9.071l2.742 1.567 2.742-1.567L4.25 7.504ZM7.5 9.933l-2.75 1.571v3.134l2.75-1.571V9.933Zm1 3.134 2.75 1.571v-3.134L8.5 9.933v3.134Zm.508-3.996 2.742 1.567 2.742-1.567-2.742-1.567-2.742 1.567Zm2.242-2.433V3.504L8.5 5.076V8.21l2.75-1.572ZM7.5 8.21V5.076L4.75 3.504v3.134L7.5 8.21ZM5.258 2.643 8 4.21l2.742-1.567L8 1.076 5.258 2.643ZM15 9.933l-2.75 1.571v3.134L15 13.067V9.933ZM3.75 14.638v-3.134L1 9.933v3.134l2.75 1.571Z" />
                                    </svg>
                                    Stock <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16"
                                        fill="currentColor" class="bi bi-caret-down-fill" viewBox="0 0 16 16">
                                        <path
                                            d="M7.247 11.14 2.451 5.658C1.885 5.013 2.345 4 3.204 4h9.592a1 1 0 0 1 .753 1.659l-4.796 5.48a1 1 0 0 1-1.506 0z" />
                                    </svg></a>
                            </li>
                        </div>


                    </ul>
                </div>
            </div>
        </nav>
    </section>



    {% block content %}
    <section id="master_section">
        <div id="carouselExample" class="carousel slide">
            <div class="carousel-inner">
                <div class="carousel-item active">
                    <img style="height: 590px;"
                        src="https://img.global.news.samsung.com/in/wp-content/uploads/2022/09/13197_TV_Banner_3000x2000.jpg"
                        class="d-block w-100" alt="...">
                </div>
                <div class="carousel-item">
                    <img style="height: 590px;"
                        src="https://idestiny.in/wp-content/uploads/2023/07/iPhone_Web-banner-3-01-min-1024x577.png"
                        class="d-block w-100" alt="...">
                </div>
                <div class="carousel-item">
                    <img style="height: 590px;"
                        src="https://img.global.news.samsung.com/in/wp-content/uploads/2022/05/KV_Big-TV-days-1920x1080.jpg"
                        class="d-block w-100" alt="...">
                </div>
            </div>
            <button class="carousel-control-prev" type="button" data-bs-target="#carouselExample" data-bs-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Previous</span>
            </button>
            <button class="carousel-control-next" type="button" data-bs-target="#carouselExample" data-bs-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Next</span>
            </button>
        </div>
    </section>
    {% endblock %}





    <!-- BootstrapJs v5.3.0 -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe"
        crossorigin="anonymous"></script>

    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script>
        $(document).ready(function () {
            $('.category-emt').hover(
                function () {
                    $('#category-hover').css('visibility', 'visible');
                },
                function () {
                    $('#category-hover').css('visibility', 'hidden');
                }
            );
        });
    </script>

</body>

</html>

ecom_admin/templates/ecom_admin/approve sellers.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
<h1>approve sellers</h1>
</body>
</html>

ecom_admin/templates/ecom_admin/home.html
{% extends 'ecom_admin/admin_master.html' %}


{% block content %}
<div class=" pt-4 container bg-body-tertiary">

    <!-- Page Heading -->
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">Admin Dashboard</h1>
        {% comment %} <a href="#" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm"><i
                class="fas fa-download fa-sm text-white-50"></i> Generate Report</a> {% endcomment %}
    </div>

    <!-- Content Row -->
    <div class="row">

        <!-- customers Card Example -->
        <div class="col-xl-3 col-md-6 mb-4">
            <div class="card border-left-primary shadow h-100 py-2">
                <div class="card-body">
                        <div class="row no-gutters align-items-center">
                            <div class="col mr-2">
                                <div class=" text-xs font-weight-bold text-primary text-uppercase mb-1">
                                    CUSTOMERS
                                </div>
                                <div class="h5 mb-0 font-weight-bold text-gray-800">{{ c_count }}</div>
                            </div>
                            <div class="col-auto">
                                <i class="fas fa-calendar fa-2x text-gray-300"></i>
                            </div>
                </div>
            </div>
        </div>
    </div>

    <!-- sellers Card Example -->
    <div class="col-xl-3 col-md-6 mb-4">
        <div class="card border-left-success shadow h-100 py-2">
            <div class="card-body">
                <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                        <div class="text-xs font-weight-bold text-success text-uppercase mb-1">
                            SELLERS</div>
                        <div class="h5 mb-0 font-weight-bold text-gray-800">{{ s_count }}</div>
                    </div>
                    <div class="col-auto">
                        <i class="fas fa-dollar-sign fa-2x text-gray-300"></i>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Total Products Card Example -->
    <div class="col-xl-3 col-md-6 mb-4">
        <div class="card border-left-info shadow h-100 py-2">
            <div class="card-body">
                <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                        <div class="text-xs font-weight-bold text-info text-uppercase mb-1">TOTAL PRODUCTS
                        </div>
                        <div class="row no-gutters align-items-center">
                            <div class="col-auto">
                                <div class="h5 mb-0 mr-3 font-weight-bold text-gray-800">{{ p_count }}</div>
                            </div>
                            <div class="col">
                                <div class="progress progress-sm mr-2">
                                    <div class="progress-bar bg-info" role="progressbar" style="width: 50%"
                                        aria-valuenow="50" aria-valuemin="0" aria-valuemax="100"></div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-auto">
                        <i class="fas fa-clipboard-list fa-2x text-gray-300"></i>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Total Orders Card Example -->
    <div class="col-xl-3 col-md-6 mb-4">
        <div class="card border-left-warning shadow h-100 py-2">
            <div class="card-body">
                <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                        <div class="text-xs font-weight-bold text-warning text-uppercase mb-1">
                            TOTAL ORDERS</div>
                        <div class="h5 mb-0 font-weight-bold text-gray-800">18</div>
                    </div>
                    <div class="col-auto">
                        <i class="fas fa-comments fa-2x text-gray-300"></i>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Content Row -->

<div class="row">

    <!-- Area Chart -->
    <div class="col-xl-8 col-lg-7">
        <div class="card shadow mb-4">
            <!-- Card Header - Dropdown -->
            <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                <h6 class="m-0 font-weight-bold text-primary">Active Customers</h6>
                <div class="dropdown no-arrow">
                    <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown"
                        aria-haspopup="true" aria-expanded="false">
                        <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in"
                        aria-labelledby="dropdownMenuLink">
                        <div class="dropdown-header">Dropdown Header:</div>
                        <a class="dropdown-item" href="#">Action</a>
                        <a class="dropdown-item" href="#">Another action</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="#">Something else here</a>
                    </div>
                </div>
            </div>
            <!-- Card Body -->
            <div class="card-body">
                <div class="chart-area">
                    <canvas id="myAreaChart"></canvas>
                </div>
            </div>
        </div>
    </div>

    <!-- Pie Chart -->
    <div class="col-xl-4 col-lg-5">
        <div class="card shadow mb-4">
            <!-- Card Header - Dropdown -->
            <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                <h6 class="m-0 font-weight-bold text-primary">Stock</h6>
                <div class="dropdown no-arrow">
                    <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown"
                        aria-haspopup="true" aria-expanded="false">
                        <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in"
                        aria-labelledby="dropdownMenuLink">
                        <div class="dropdown-header">Dropdown Header:</div>
                        <a class="dropdown-item" href="#">Action</a>
                        <a class="dropdown-item" href="#">Another action</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="#">Something else here</a>
                    </div>
                </div>
            </div>
            <!-- Card Body -->
            <div class="card-body">
                <div class="chart-pie pt-4 pb-2">
                    <canvas id="myPieChart"></canvas>
                </div>
                <!-- <div class="mt-4 text-center small">
                        <span class="mr-2">
                            <i class="fas fa-circle text-primary"></i> Direct
                        </span>
                        <span class="mr-2">
                            <i class="fas fa-circle text-success"></i> Social
                        </span>
                        <span class="mr-2">
                            <i class="fas fa-circle text-info"></i> Referral
                        </span>
                    </div> -->
            </div>
        </div>
    </div>
</div>
</div>

{%endblock%}

ecom_admin/templates/ecom_admin/recent updates.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    recent updates
</body>
</html>

ecom_admin/templates/ecom_admin/remove customer.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    remove customer
</body>
</html>

ecom_admin/templates/ecom_admin/remove product.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    remove product
</body>
</html>

ecom_admin/templates/ecom_admin/remove seller.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    remove seller
</body>
</html>

ecom_admin/templates/ecom_admin/view customers.html
{% extends 'ecom_admin/admin_master.html' %}

{% load static %}

{% block title %}
<title>View Customers</title>
<link rel="stylesheet" href="{% static 'style/view_customer.css' %}">
{% endblock %}


{% block content %}

<div class="container">

    <div class="title_div">

        <h1>VIEW CUSTOMERS</h1>

    </div>

    <div class="table_div">

        <table class="table table-striped">
            <thead>
                <tr>
                    <th scope="col">ID</th>
                    <th scope="col">NAME</th>
                    <th scope="col">ADDRESS</th>
                    <th scope="col">EMAIL</th>

                </tr>
            </thead>
            <tbody>
                {% for customer in customers %}
                <tr>
                    <th scope="row">{{ customer.id | title }}</th>
                    <td>{{ customer.c_name | title }}</td>
                    <td>{{ customer.c_address | title }}</td>
                    <td>{{ customer.c_email | title }}</td>
                    <td>{{ customer.c_mobile | title }}</td>
                </tr>
                {% endfor %}

            </tbody>
        </table>

    </div>

</div>

{%endblock%}

ecom_admin/templates/ecom_admin/view orders.html
{% extends 'ecom_admin/admin_master.html' %} 

{% block content %}


{%endblock%}

ecom_admin/templates/ecom_admin/view products.html
{% extends 'ecom_admin/admin_master.html' %} 

{% block content %}


{%endblock%}

ecom_admin/templates/ecom_admin/view sellers.html
{% extends 'ecom_admin/admin_master.html' %} 

{% load static %}

{% block title %}
<title>View Sellers</title>
<link rel="stylesheet" href="{% static 'style/view_customer.css' %}">
{% endblock %}


{% block content %}

<div class="container">

    <div class="title_div">

        <h1>VIEW SELLERS</h1>

    </div>

    <div class="table_div">

        <table class="table table-striped">
            <thead>
                <tr>
                    <th scope="col">ID</th>
                    <th scope="col">IMAGE</th>
                    <th scope="col">NAME</th>
                    <th scope="col">ADDRESS</th>
                    <th scope="col">EMAIL</th>
                    <th scope="col">MOBILE</th>


                </tr>
            </thead>
            <tbody>
                {% for seller in sellers %}
                <tr>
                    <th scope="row">{{ seller.id | title }}</th>
                    <td><img src="{{seller.s_image.url}}" width="80px" height="80px" style="border-radius: 50%;"></td>
                    <td>{{ seller.s_name | title }}</td>
                    <td>{{ seller.s_address | title }}</td>
                    <td>{{ seller.s_email | title }}</td>
                    <td>{{ seller.s_mobile | title }}</td>
                </tr>
                {% endfor %}

            </tbody>
        </table>

    </div>

</div>
{%endblock%}