common/urls.py
from django.urls import path
from . import views
app_name = 'common'

urlpatterns = [
    path('comadminlogin', views.admin_login, name='admin_login'),
    path('customerlogin', views.customer_login, name='customer_login'),
    path('customersignup', views.customer_signup, name='customer_signup'),
    path('', views.project_home, name='project_home'),
    path('sellerlogin', views.seller_login, name='seller_login'),
    path('sellersignup', views.seller_signup, name='seller_signup'),
    path('mastercommon', views.master_common, name='master_common'),
    path('test', views.test, name='test'),
    path('email_exist', views.email_exist, name='email_exist'),



]

customer/urls.py
from django.urls import path
from . import views
app_name='customer'
urlpatterns=[
    path('customer_home',views.customer_home,name='home'),
    path('ccheckout',views.customer_checkout,name='checkout'),
    path('cmycart',views.customer_mycart,name='mycart'),
    path('cchangepassword',views.customer_changepassword,name='changepassword'),
    path('cproductdetails/<int:p_id>',views.customer_productdetails,name='productdetails'),
    path('cprofile',views.customer_profile,name='customer_profile'),
    path('cmyorders',views.customer_myorders,name='myorders'),
    path('c_logout',views.customer_logout,name='customer_logout'),
    path('master_customer',views.master_customer,name='master_customer'),
    path('change_quantity',views.change_quantity,name ='change_quantity'),
    path('info',views.info,name ='info'),
    path('delete_item/<int:item_id>',views.delete_item, name='delete_item'),
    path('total_price',views.total_price, name='total_price'),


]

ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('customer/', include('customer.urls')),
    path('', include('common.urls')),
    path('ecom_admin/', include('ecom_admin.urls')),
    path('seller/', include('seller.urls')),

]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

common/models.py
from django.db import models

# Create your models here.

class Customer(models.Model) :
    c_name = models.CharField(max_length = 50)
    c_email = models.CharField(max_length = 50)
    c_address = models.CharField(max_length = 100)
    c_mobile = models.BigIntegerField()
    c_gender = models.CharField(max_length = 10)
    c_password = models.CharField(max_length = 30, default = '')
    c_status = models.CharField(max_length = 25, default = 'active')
        
    class Meta : 
        db_table = 'customer'

class Seller(models.Model) :
    s_name = models.CharField(max_length = 50)
    s_email = models.CharField(max_length = 50)
    s_address = models.CharField(max_length = 100)
    s_mobile = models.BigIntegerField()
    s_username = models.IntegerField(default = 0)
    s_password = models.CharField(max_length = 50)
    s_bank_name = models.CharField(max_length = 50)
    s_bank_branch = models.CharField(max_length = 50)
    s_ifsc_code = models.CharField(max_length = 50)
    s_acc_number = models.BigIntegerField()
    s_image = models.ImageField(upload_to = 'seller/')
    s_status = models.CharField(max_length = 20, default = 'pending')

    class Meta : 
        db_table = 'seller'

class Admin(models.Model):
    a_username = models.CharField(max_length = 50)
    a_password = models.CharField(max_length = 20)

    class Meta:
        db_table = 'admin'

 
    

common/views.py
from django.conf import settings
from django.http import JsonResponse
from django.shortcuts import render,redirect
from random import randint
from .models import Customer, Seller
from django.core.mail import send_mail


def admin_login(request):
    return render(request, 'common/admin login.html')


def customer_login(request):

    msg = ''
    if request.method == 'POST':
        cemail = request.POST['email']
        cpassword = request.POST['password']
        try :
            new_customer = Customer.objects.get(c_email = cemail,c_password = cpassword)
            request.session['customer'] = new_customer.id
            return redirect('customer:home')

        except:
            msg = 'Invalid credentials'
    
    return render(request, 'common/customer login.html',{'message':msg})


def customer_signup(request):
    msg = ''

    if request.method == 'POST' :
        cname = request.POST['customer_name']
        cemail = request.POST['email']
        cmobile = request.POST['mobile_number']
        caddress = request.POST['address']
        cgender = request.POST['gender']
        cpassword = request.POST['password']

        try:
            new_customer = Customer(
                c_name = cname, 
                c_email = cemail, 
                c_mobile = cmobile,
                c_address = caddress, 
                c_gender = cgender,
                c_password = cpassword
                )
            new_customer.save()
            msg = 'Successfully Registered Customer'
        except:
            msg = 'Invalid Credentials'


    return render(request, 'common/customer signup.html', {'message':msg})


def project_home(request):
    return render(request, 'common/project home.html')


def seller_login(request):
    msg = ''

    if request.method == 'POST' :

        susername = request.POST['username']
        spassword = request.POST['password']
        try:
            seller = Seller.objects.get(s_username=susername, s_password = spassword)
            request.session['seller'] = seller.id
            return redirect('seller:seller_home')
        except:
            msg = 'Invalid Credentials'
    return render(request, 'common/seller login.html',{'message':msg})


def seller_signup(request):
    msg = ''
    if request.method == 'POST' :
        sname = request.POST['seller_name']
        smobile = request.POST['seller_mobile']
        semail = request.POST['seller_email']
        saddress = request.POST['seller_address']
        sbankname = request.POST['seller_bank_name']
        saccountnumb = request.POST['seller_account_number']
        sbankbranch = request.POST['seller_bank_branch']
        sifsccode = request.POST['seller_ifsc']
        simage = request.FILES['seller_pic']
        susername = randint(1000,9999)
        spassword = 'sel-'+sname.lower()+str(susername)

        seller = Seller(
            s_name = sname,
            s_mobile = smobile,
            s_email = semail,
            s_address = saddress,
            s_bank_name = sbankname,
            s_acc_number = saccountnumb,
            s_bank_branch = sbankbranch,
            s_ifsc_code = sifsccode,
            s_image = simage,
            s_username = susername,
            s_password = spassword)
        seller.save()
        
        msg = 'seller registered successfully'

        subject = 'account name and password'
        message = 'hai your username is '+str(susername)+'and your password is '+spassword
        email_from = settings.EMAIL_HOST_USER
        send_mail(
            subject,
            message,
            email_from,
            [semail],
            fail_silently = False
        )
        
    return render(request, 'common/seller signup.html',{'message':msg})

def master_common(request):
    return render(request, 'common/master_common.html')         

def test(request):
    return render(request, 'common/test.html')

def email_exist(request):
    email = request.POST['email_data']
    email_exists = Customer.objects.filter(c_email = email).exists()
    return JsonResponse({'email_exists':email_exists})

     

common/templates/common/admin login.html
{% extends 'common/master_common.html' %}
{% load static %}
{% block title %}
<title>Admin Login</title>
<link rel="stylesheet" href="{% static 'style/admin_login.css' %}">
{% endblock %}
{% block content %}
<div>
    <div class="container">
        <h1>Admin Login</h1><br>
        <p>Enter your login details to continue</p>
        <form method="POST">
            {% csrf_token %}
            {{message}}
            <div>
                <label for="inputEmail4" class="form-label">User Name</label>
                <input type="text" class="form-control" id="inputEmail4" placeholder="Enter your User name"
                    name="username">
            </div>
            <div>
                <label for="inputPassword4" class="form-label">Password</label>
                <input type="password" class="form-control" id="inputPassword4" placeholder="Enter your Password"
                    name="password">
            </div>
            <br>
            <div>
                <button type="submit" class="btn btn-success" a>Login</button>
            </div><br>
        </form>
    </div>
</div>
{% endblock %}

common/templates/common/customer login.html
{% extends 'common/master_common.html' %}
{% load static %}
{% block title %}
<title>Customer Login</title>
<link rel="stylesheet" href="{% static 'style/cust_login_style.css' %}">
{% endblock %}
{% block content %}
<div>
    <div class="container">
        <h1>Customer Login</h1><br>
        <p>Enter your login details to continue</p>
        <form method="POST">
            {% csrf_token %}
            <span>{{message}}</span>
            <div>
                <label for="inputEmail4" class="form-label">Email</label>
                <input type="email" class="form-control" id="inputEmail4" placeholder="Enter your E-mail Address"
                    name="email">
            </div>
            <div>
                <label for="inputPassword4" class="form-label">Password</label>
                <input type="password" class="form-control" id="inputPassword4" placeholder="Enter your Password"
                    name="password">
            </div>
            <a href="{% url 'common:customer_signup' %}">New to ShopEhuB?</a>
            <a href="#" id="forgot_pwd_id">Forgot Password?</a>
            <br>
            <div>
                <button type="submit" class="btn btn-success" a>Login</button>
            </div><br>
            <h6>
                By continuing, you agree to Shop-E-huB's <br> <a href="#conditions_of_use">Conditions of Use</a>
            </h6>
        </form>
    </div>
</div>
{% endblock %}

common/templates/common/customer signup.html
{% extends 'common/master_common.html' %}
{% load static %}
{% block title %}
<title>Customer Registration</title>
<script src=" https://code.jquery.com/jquery-3.6.4.js" integrity="sha256-a9jBBRygX1Bh5lt8GZjXDzyOB+bWve9EiO7tROUtj/E="
    crossorigin="anonymous">
    </script>
<link rel="stylesheet" href="{% static 'style/cust_signup_style.css' %}">
{% endblock %}


{% block content %}
<div>
    <div class="container">
        <h1>
            Customer Sign Up
        </h1>
        <p>Enter your details to Sign Up</p>

        <form method="POST">
            {% csrf_token %}
            <span>{{message}}</span>
            <div>
                <label for="input_name">Your Name</label>
                <input type="text" class="form-control" id="cust_name" placeholder="Enter Your Name"
                    name="customer_name">
            </div>
            <div>
                <label for="input_mobile" class="form-label">Your Mobile Number</label>
                <input type="text" class="form-control" id="cust_mobile" placeholder="Enter Your Mobile Number"
                    name="mobile_number">
            </div>
            <div>
                <label for="input_mobile" class="form-label">Address</label>
                <textarea name="address" class="form-control" id="cust_address" cols="30" rows="3"></textarea>
            </div>
            <div>
                <label for="inputEmail4" class="form-label">Email</label>
                <input type="email" class="form-control" id="cust_email" placeholder="Enter your E-mail Address"
                    name="email">
                <span id="email_err"></span>
            </div>
            <div>
                <label for="inputPassword4" class="form-label">Password</label>
                <input type="password" class="form-control" id="cust_password" placeholder="Atleast 6 characters"
                    name="password">
            </div>
            <div id="radio_div_id">
                <label for="inputPassword4" class="form-label">Gender</label><br>
                <label for="male">male</label>
                <input type="radio" id="male" name="gender" value="male">
                <label for="female">female</label>
                <input type="radio" id="female" name="gender" value="female">
            </div>
            <br>
            <div>
                <button id="btn_submit" type="submit" class="btn btn-success">Sign Up</button>
            </div><br>
            <h6>
                Already a member? <a href="{% url 'common:customer_login' %}">Login</a>  here
            </h6>
        </form>
    </div>
</div>
<!-- <script>

    var cust_name = document.getElementById('cust_name');
    var cust_mobile = document.getElementById('cust_mobile').value;
    var cust_email = document.getElementById('cust_email').value;
    var cust_password = document.getElementById('cust_password').value;
    var s_name = document.getElementById('name_error_msg_id')

    function customer_validation() {



        if (cust_name.value == "") {                                                       //if nothing is entered in the email field
            s_name.innerHTML = "Username must be filled out"; //required error message is inserted to the particular input text
            document.getElementById('cust_name').style.border = '1px solid red';                      //to make the input field's border in to reddish colour
            return false;

        } 
        else{
            s_name.innerHTML = '';                           //since the condition is false the form gets submitted                      
            document.getElementById('cust_name').style.border = '';                      //to make the input field's border in to reddish colour


        }

        // if (cust_name.length < 8) {                                      //if nothing is entered in the email field

        //     document.getElementById('name_error_msg_id').innerHTML = "must be atleast 8 characters"; //required error message is inserted to the particular input text
        //     document.getElementById('cust_name').style.border =  '1px solid red';                      //to make the input field's border in to reddish colour
        //     return false;

        // } else {

        //     document.getElementById('name_error_msg_id').innerHTML = "";                           //since the condition is false the form gets submitted
        //     document.getElementById('cust_name').style.border = "";

        // }

    }

</script> -->
<script>
    $(document).ready(function () {
        $.ajaxSetup({
            headers: {
                "X-CSRFToken": $('[name=csrfmiddlewaretoken]').val()
            }
        })
        $('#cust_email').change(function () {
            var email = $('#cust_email').val()
            $.ajax({
                type: 'POST',
                url: '{% url "common:email_exist" %}',
                data: {
                    'email_data': email
                },
                success: function (response) {

                    let res = response.email_exists
                    if (res == true) {
                        $('#email_err').html('Email exists')
                        $('#email_err').css('color', 'red')
                        $('#btn_submit').attr('disabled', true)

                    }
                    else {
                        $('#email_err').html('')
                        $('#btn_submit').attr('disabled', false)
                    }


                }
            })

        })
    })
</script>
{% endblock %}

common/templates/common/master_common.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style/masterstyle.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link
        href="https://fonts.googleapis.com/css2?family=Clicker+Script&family=Jost:wght@100;400;500;600&family=Poppins&display=swap"
        rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"
        integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.min.js"
        integrity="sha384-mQ93GR66B00ZXjt0YO5KlohRA5SY2XofN4zfuZxLkoj1gXtW8ANNCe9d5Y3eG5eD"
        crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/9edefc9b63.js" crossorigin="anonymous"></script>
    {% block title %}
    <title>Master common</title>
    {% endblock %}



</head>

<body>
    <div>
        <!-- -------------------------start of first heading------------------------------------ -->
        <div class="first_heading_div">
            <ul class="heading_ul">
                <li>
                    <a href="#">About</a>
                </li>
                <li>
                    <a href="#">
                        Privacy
                    </a>
                </li>
                <li>
                    <a href="#">
                        FAQ
                    </a>
                </li>
                <li>
                    <a href="#">
                        Careers
                    </a>
                </li>
                <li>
                    <a href="#">
                        Track your Order
                    </a>
                </li>
                <li>
                    <a href="#">
                        My Wishlist
                    </a>
                </li>
                <div class="ul_inside_div">
                    <a href="#"><i class="fa-brands fa-facebook"></i></a>
                    <a href="#"><i class="fa-brands fa-twitter"></i></a>
                    <a href="#"><i class="fa-brands fa-instagram"></i></a>
                    <a href="#"><i class="fa-brands fa-whatsapp"></i></a>
                    <a href="#"><i class="fa-brands fa-linkedin"></i></a>
                </div>

            </ul>

        </div>
        <!-- -------------------------end of first heading------------------------------------ -->

        <!-- -------------------------start of navbar------------------------------------ -->
        <nav class="navbar navbar-expand-lg bg-success">
            <div class="container-fluid">
                <a class="navbar-brand text-light" href="#">
                    <b>SHOP</b>EHUB</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse navbar_div">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0 text-light navbar_div_ul">
                        <li class="nav-item">
                            <a class="nav-link" aria-current="page" href="{% url 'common:project_home' %}">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" aria-current="page" href="{% url 'common:project_home' %}">Men</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" aria-current="page" href="{% url 'common:project_home' %}">Women</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" aria-current="page" href="{% url 'common:project_home' %}">Kids</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" aria-current="page" href="{% url 'common:project_home' %}">Contact</a>
                        </li>
                    </ul>
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0 text-light navbar_div_ul" id="div_id_2">
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                                data-bs-toggle="dropdown" aria-expanded="false">
                                <i class="fa-solid fa-user"></i>
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" href="{% url 'common:customer_login' %}">Customer Login</a>
                                </li>
                                <li><a class="dropdown-item" href="{% url 'common:customer_signup' %}">Customer Sign
                                        Up</a></li>
                                <li><a class="dropdown-item" href="{% url 'common:seller_login' %}">Seller Login</a>
                                </li>
                                <li><a class="dropdown-item" href="{% url 'common:seller_signup' %}">Seller Sign Up</a>
                                </li>

                            </ul>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" aria-current="page" href="{% url 'customer:mycart' %}"> <i
                                    class="fa-solid fa-cart-shopping"></i>
                            </a>
                        </li>
                    </ul>

                </div>
            </div>
        </nav>
        <!-- -------------------------end of navbar------------------------------------ -->


        <!-- -------------------------start of second heading------------------------------------ -->

        <div class="main_heading_div">

            <h6>Sale Up To 50% Biggest Discounts. Hurry! Limited Period Registration

            </h6>

        </div>
        <!-- -------------------------end of second heading------------------------------------ -->

        {% block content %}


        {% endblock %}
</body>

</html>

common/templates/common/project home.html
{% extends 'common/master_common.html' %}
{% load static %}
{% block title %}
<title>SHOPEHUB</title>
<link rel="stylesheet" href="{% static 'style/project_home_style.css' %}">
{% endblock %}

{% block content %}

<div id="carouselExampleAutoplaying" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-inner">
        <div class="carousel-item active carousel_div">
            <img src="{% static 'images/man-sunglasses-with-sale-sign.jpg' %}" class="d-block w-100" alt="...">
            <div class="carousel-caption d-md-block">
                <h5>Fashion Sale</h5>
                <h1>Minimal Menz Style</h1>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing <br> elit. Veritatis quod, soluta veniam
                    blanditiis rem <br> quia sint in facere tenetur. Totam cum ducimus nam. <br>
                    <a href=""><button class="btn outline">Shop Now</button></a>
            </div>
        </div>
        <div class="carousel-item carousel_div" id="carousel_div_2_id">
            <img src="{% static 'images/man-floating-with-shopping-bags.jpg' %}" class="d-block w-100" alt="...">
            <div class="carousel-caption d-md-block">
                <h5>Fashion Sale</h5>
                <h1>Minimal Menz Style</h1>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing <br> elit. Veritatis quod, soluta veniam
                    blanditiis rem <br> quia sint in facere tenetur. Totam cum ducimus nam. <br>
                    <a href=""><button class="btn outline">Shop Now</button></a>
            </div>
        </div>
        <div class="carousel-item carousel_div" id="carousel_div_3_id">
            <img src="{% static 'images/expressive-young-woman-posing.jpg' %}" class="d-block w-100" alt="...">
            <div class="carousel-caption d-md-block">
                <h5>Fashion Sale</h5>
                <h1>Minimal Menz Style</h1>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing <br> elit. Veritatis quod, soluta veniam
                    blanditiis rem <br> quia sint in facere tenetur. Totam cum ducimus nam. <br>
                    <a href=""><button class="btn outline">Shop Now</button></a>
            </div>
        </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleAutoplaying"
        data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleAutoplaying"
        data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
    </button>
</div>


{% endblock %}

common/templates/common/seller login.html
{% extends 'common/master_common.html' %}
{% load static %}
{% block title %}
<title>Seller Login</title>
<link rel="stylesheet" href="{% static 'style/seller_login_style.css' %}">
{% endblock %}
{% block content %}



<div>


    <div class="container">
        <h1>
            SELLER LOGIN
        </h1>
        <p>Enter your login details to continue</p>
        <form action="" method="POST">
            {% csrf_token %}
            {{message}}
            <div>
                <label for="inputEmail4" class="form-label">User Name</label>
                <input type="text" class="form-control" id="inputEmail4" placeholder="Enter your User Name"
                    name="username">
            </div>
            <div>
                <label for="inputPassword4" class="form-label">Password</label>
                <input type="password" class="form-control" id="inputPassword4" placeholder="Enter your Password"
                    name="password">
            </div>
            <a href="{% url 'common:seller_signup' %}">New to ShopEhuB?</a>
            <br>
            <div>
                <button type="submit" class="btn btn-success text-light">Login</button>
            </div><br>
        </form>
    </div>
</div>
{% endblock %}

common/templates/common/seller signup.html
{% extends 'common/master_common.html' %}
{% load static %}
{% block title %}
<title>Seller Registration</title>
<link rel="stylesheet" href="{% static 'style/seller_signup_style.css' %}">
{% endblock %}


{% block content %}
<div>
    <div class="container">
        <h1>
            SELLER REGISTRATION
        </h1>
        <form action="" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{message}}
            <div>
                <label for="input_name">Your Name</label>
                <input type="text" class="form-control" id="input_name" placeholder="Enter Your Name" name="seller_name">
            </div>
            <div>
                <label for="input_mobile" class="form-label">Your Mobile Number</label>
                <input type="number" class="form-control" id="input_mobile" placeholder="Enter Your Mobile Number" name="seller_mobile">
            </div>
            <div>
                <label for="inputEmail4" class="form-label">Email</label>
                <input type="email" class="form-control" id="inputEmail" placeholder="Enter your E-mail Address" name="seller_email">
            </div>
            <div>
                <label for="inputEmail4" class="form-label">address</label>
                <input type="text" class="form-control" id="inputEmail" placeholder="Enter your Address" name="seller_address">
            </div>
            <div>
                <label for="input_bank_name">Bank Name</label>
                <input type="text" class="form-control" id="input_bank_name" placeholder="Enter Your Bank Name" name="seller_bank_name">
            </div>
            <div>
                <label for="acc_name">Account Number</label>
                <input type="number" class="form-control" id="account_number" placeholder="Enter Your Account Number" name="seller_account_number">
            </div>
            <div>
                <label for="input_branch" class="form-label">Bank Branch</label>
                <input type="text" class="form-control" id="input_branch" placeholder="Enter Your bank branch" name="seller_bank_branch">
            </div>
            <div>
                <label for="input_ifsc" class="form-label">ifsc code</label>
                <input type="text" class="form-control" id="input_ifsc" placeholder="Enter Your ifsc code" name="seller_ifsc">
            </div><br>
            <div class="input-group mb-3">
                <input type="file" class="form-control" id="inputGroupFile02" name="seller_pic">
                <label class="input-group-text" for="inputGroupFile02">Upload</label>
            </div>
            <br>
            <div>
                <button type="submit" class="btn btn-success">Sign Up</button>
            </div><br>
        </form>
    </div>
</div>
{% endblock %}